function Hp = Highpassfilter
%HIGHPASSFILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.0 and the DSP System Toolbox 9.2.
% Generated on: 25-Jun-2017 01:04:32

% Chebyshev Type II Highpass filter designed using FDESIGN.HIGHPASS.

% All frequency values are in Hz.
Fs = 1000;  % Sampling Frequency

N     = 2;  % Order
Fstop = 30;  % Stopband Frequency
Astop = 80;  % Stopband Attenuation (dB)

% Construct an FDESIGN object and call its CHEBY2 method.
h  = fdesign.highpass('N,Fst,Ast', N, Fstop, Astop, Fs);
Hp = design(h, 'cheby2');

% [EOF]
